apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bank-statement-assistant
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - statements-pvc.yaml
