/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dependency Readiness */
        get: operations["dependency_readiness_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/months/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Month Report */
        get: operations["get_month_report_api_reports_months__month__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report Transactions */
        get: operations["get_report_transactions_api_reports_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Statements */
        get: operations["list_statements_api_statements_get"];
        put?: never;
        /** Upload Statement */
        post: operations["upload_statement_api_statements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statements/{statement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Statement */
        get: operations["get_statement_api_statements__statement_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statements/{statement_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess Statement */
        post: operations["reprocess_statement_api_statements__statement_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statements/{statement_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Statement */
        post: operations["retry_statement_api_statements__statement_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_api_transactions__transaction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}/classification/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Classification */
        post: operations["accept_classification_api_transactions__transaction_id__classification_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct Transaction */
        post: operations["correct_transaction_api_transactions__transaction_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transaction History */
        get: operations["transaction_history_api_transactions__transaction_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revert Transaction */
        post: operations["revert_transaction_api_transactions__transaction_id__revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_statement_api_statements_post */
        Body_upload_statement_api_statements_post: {
            /** Account Reference */
            account_reference: string;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** BreakdownItemResponse */
        BreakdownItemResponse: {
            /** Amount */
            amount: string;
            /** Label */
            label: string;
            /** Transaction Count */
            transaction_count: number;
        };
        /** ClassificationAcceptanceRequest */
        ClassificationAcceptanceRequest: {
            /** Classification Id */
            classification_id: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** Reason */
            reason?: string | null;
        };
        /** CorrectionRecordResponse */
        CorrectionRecordResponse: {
            /** Created At */
            created_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Origin */
            origin: string;
            /** Previous Revision */
            previous_revision: number;
            /** Reason */
            reason: string;
            /** Revision */
            revision: number;
            /**
             * Transaction Id
             * Format: uuid
             */
            transaction_id: string;
            values: components["schemas"]["TransactionValuesResponse"];
        };
        /** CurrencySummaryResponse */
        CurrencySummaryResponse: {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Transaction Count */
            transaction_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
        };
        /** LargestTransactionResponse */
        LargestTransactionResponse: {
            /** Amount */
            amount: string;
            /**
             * Booking Date
             * Format: date
             */
            booking_date: string;
            /** Counterparty */
            counterparty: string | null;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reporting Category */
            reporting_category: string | null;
        };
        /** MonthlyReportResponse */
        MonthlyReportResponse: {
            /** Category Breakdown */
            category_breakdown: components["schemas"]["BreakdownItemResponse"][];
            /** Counterparty Breakdown */
            counterparty_breakdown: components["schemas"]["BreakdownItemResponse"][];
            /** Largest Transactions */
            largest_transactions: components["schemas"]["LargestTransactionResponse"][];
            /** Month */
            month: string;
            /** Payment Channel Breakdown */
            payment_channel_breakdown: components["schemas"]["BreakdownItemResponse"][];
            quality: components["schemas"]["ReportQualityResponse"];
            totals: components["schemas"]["ReportTotalsResponse"];
            transfers: components["schemas"]["TransferSummaryResponse"];
        };
        /**
         * ProcessingStage
         * @enum {string}
         */
        ProcessingStage: "accept" | "extract_text" | "extract_transactions" | "validate" | "revalidate" | "classify" | "review" | "publish_state";
        /** ReportOverviewResponse */
        ReportOverviewResponse: {
            /** Previous Period Change */
            previous_period_change: string | null;
            totals: components["schemas"]["ReportTotalsResponse"];
        };
        /** ReportQualityResponse */
        ReportQualityResponse: {
            /** Is Provisional */
            is_provisional: boolean;
            /** Provisional Count */
            provisional_count: number;
            /** Unresolved Amount */
            unresolved_amount: string;
            /** Unresolved Count */
            unresolved_count: number;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Months */
            months: components["schemas"]["MonthlyReportResponse"][];
            /** Non Eur */
            non_eur: components["schemas"]["CurrencySummaryResponse"][];
            /** Non Eur Transactions */
            non_eur_transactions: components["schemas"]["LargestTransactionResponse"][];
            overview: components["schemas"]["ReportOverviewResponse"];
        };
        /** ReportTotalsResponse */
        ReportTotalsResponse: {
            /** Gross Spending */
            gross_spending: string;
            /** Income */
            income: string;
            /** Net Account Flow */
            net_account_flow: string;
            /** Net Cash Flow */
            net_cash_flow: string;
            /** Net Spending */
            net_spending: string;
            /** Refunds */
            refunds: string;
            /** Transfer In */
            transfer_in: string;
            /** Transfer Out */
            transfer_out: string;
        };
        /** ReportTransactionPageResponse */
        ReportTransactionPageResponse: {
            /** Items */
            items: components["schemas"]["ReportTransactionResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ReportTransactionResponse */
        ReportTransactionResponse: {
            /**
             * Booking Date
             * Format: date
             */
            booking_date: string;
            /** Counterparty */
            counterparty: string | null;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Movement Kind */
            movement_kind: string | null;
            /** Payment Channel */
            payment_channel: string | null;
            /** Reporting Category */
            reporting_category: string | null;
            /** Signed Amount */
            signed_amount: string;
            /** Transfer Scope */
            transfer_scope: ("own_account" | "external_party" | "unknown") | null;
        };
        /** StatementResponse */
        StatementResponse: {
            /** Account Reference */
            account_reference: string;
            /** Created At */
            created_at: string | null;
            current_stage: components["schemas"]["ProcessingStage"];
            /** Extraction Result */
            extraction_result: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Error Code */
            last_error_code: string | null;
            /** Original Filename */
            original_filename: string;
            /** Page Count */
            page_count: number;
            /** Review Findings */
            review_findings: {
                [key: string]: unknown;
            }[];
            /**
             * Status
             * @enum {string}
             */
            status: "processing" | "needs_review" | "ready" | "failed" | "archived";
            /** Validation Result */
            validation_result: {
                [key: string]: unknown;
            } | null;
        };
        /** TransactionCorrectionRequest */
        TransactionCorrectionRequest: {
            /** Booking Date */
            booking_date?: string | null;
            /** Counterparty */
            counterparty?: string | null;
            /** Currency */
            currency?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Expected Revision
             * @default 0
             */
            expected_revision: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** Movement Kind */
            movement_kind?: ("Expense" | "Income" | "Transfer" | "Refund" | "Fee") | null;
            /** Note */
            note?: string | null;
            /** Payment Channel */
            payment_channel?: ("MB WAY" | "Card" | "Bank Transfer" | "Direct Debit" | "Cash Withdrawal" | "Other") | null;
            /** Reason */
            reason: string;
            /** Reporting Category */
            reporting_category?: ("Groceries" | "Restaurants & Cafes" | "Housing" | "Utilities" | "Transport" | "Health" | "Insurance" | "Subscriptions" | "Shopping" | "Leisure" | "Travel" | "Education" | "Gifts & Donations" | "Taxes" | "Other Expense" | "Salary" | "Interest" | "Other Income" | "Bank Fees") | null;
            /** Signed Amount */
            signed_amount?: number | string | null;
            /** Transfer Scope */
            transfer_scope?: ("own_account" | "external_party" | "unknown") | null;
        };
        /** TransactionPageResponse */
        TransactionPageResponse: {
            /** Items */
            items: components["schemas"]["TransactionResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /**
             * Booking Date
             * Format: date
             */
            booking_date: string;
            /** Classification Confidence */
            classification_confidence: number | null;
            /** Classification Id */
            classification_id?: number | null;
            /** Classification Provenance */
            classification_provenance: {
                [key: string]: unknown;
            } | null;
            /**
             * Classification Resolution
             * @default pending
             * @enum {string}
             */
            classification_resolution: "pending" | "accepted" | "corrected";
            /** Classification Status */
            classification_status: string;
            /** Confidence */
            confidence: number;
            /**
             * Correction Revision
             * @default 0
             */
            correction_revision: number;
            /** Counterparty */
            counterparty?: string | null;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /** Evidence Line End */
            evidence_line_end: number | null;
            /** Evidence Line Start */
            evidence_line_start: number | null;
            /** Evidence Page Number */
            evidence_page_number: number | null;
            /** Evidence Quote */
            evidence_quote: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Movement Kind */
            movement_kind: string | null;
            /** Note */
            note?: string | null;
            /** Original Booking Date */
            original_booking_date?: string | null;
            /** Original Counterparty */
            original_counterparty?: string | null;
            /** Original Currency */
            original_currency?: string | null;
            /** Original Description */
            original_description?: string | null;
            /** Original Movement Kind */
            original_movement_kind?: string | null;
            /** Original Note */
            original_note?: string | null;
            /** Original Payment Channel */
            original_payment_channel?: string | null;
            /** Original Reporting Category */
            original_reporting_category?: string | null;
            /** Original Signed Amount */
            original_signed_amount?: string | null;
            /** Original Transfer Scope */
            original_transfer_scope?: ("own_account" | "external_party" | "unknown") | null;
            /** Payment Channel */
            payment_channel: string | null;
            /** Reporting Category */
            reporting_category: string | null;
            /** Review Findings */
            review_findings: {
                [key: string]: string;
            }[];
            /** Signed Amount */
            signed_amount: string;
            /** Source Ordinal */
            source_ordinal: number;
            /** Statement Filename */
            statement_filename: string;
            /**
             * Statement Id
             * Format: uuid
             */
            statement_id: string;
            /**
             * Statement Status
             * @enum {string}
             */
            statement_status: "processing" | "needs_review" | "ready" | "failed" | "archived";
            /** Transfer Scope */
            transfer_scope?: ("own_account" | "external_party" | "unknown") | null;
        };
        /** TransactionRevertRequest */
        TransactionRevertRequest: {
            /**
             * Expected Revision
             * @default 0
             */
            expected_revision: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** Reason */
            reason: string;
            /** Target Revision */
            target_revision: number;
        };
        /** TransactionValuesResponse */
        TransactionValuesResponse: {
            /**
             * Booking Date
             * Format: date
             */
            booking_date: string;
            /** Counterparty */
            counterparty: string | null;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /** Movement Kind */
            movement_kind: string | null;
            /** Note */
            note: string | null;
            /** Payment Channel */
            payment_channel: string | null;
            /** Reporting Category */
            reporting_category: string | null;
            /** Signed Amount */
            signed_amount: string;
            /** Transfer Scope */
            transfer_scope: ("own_account" | "external_party" | "unknown") | null;
        };
        /** TransferSummaryResponse */
        TransferSummaryResponse: {
            /** Count */
            count: number;
            /** External Total */
            external_total: string;
            /** Incoming */
            incoming: string;
            /** Outgoing */
            outgoing: string;
            /** Own Account Total */
            own_account_total: string;
            /** Total */
            total: string;
            /** Unknown Total */
            unknown_total: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    dependency_readiness_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_report_api_reports_get: {
        parameters: {
            query?: {
                month_from?: string | null;
                month_to?: string | null;
                statement_id?: string | null;
                currency?: string;
                reporting_category?: ("Groceries" | "Restaurants & Cafes" | "Housing" | "Utilities" | "Transport" | "Health" | "Insurance" | "Subscriptions" | "Shopping" | "Leisure" | "Travel" | "Education" | "Gifts & Donations" | "Taxes" | "Other Expense" | "Salary" | "Interest" | "Other Income" | "Bank Fees") | null;
                movement_kind?: ("Expense" | "Income" | "Transfer" | "Refund" | "Fee") | null;
                payment_channel?: ("MB WAY" | "Card" | "Bank Transfer" | "Direct Debit" | "Cash Withdrawal" | "Other") | null;
                counterparty?: string | null;
                include_provisional?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_month_report_api_reports_months__month__get: {
        parameters: {
            query?: {
                statement_id?: string | null;
                currency?: string;
                reporting_category?: ("Groceries" | "Restaurants & Cafes" | "Housing" | "Utilities" | "Transport" | "Health" | "Insurance" | "Subscriptions" | "Shopping" | "Leisure" | "Travel" | "Education" | "Gifts & Donations" | "Taxes" | "Other Expense" | "Salary" | "Interest" | "Other Income" | "Bank Fees") | null;
                movement_kind?: ("Expense" | "Income" | "Transfer" | "Refund" | "Fee") | null;
                payment_channel?: ("MB WAY" | "Card" | "Bank Transfer" | "Direct Debit" | "Cash Withdrawal" | "Other") | null;
                counterparty?: string | null;
                include_provisional?: boolean;
            };
            header?: never;
            path: {
                month: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_transactions_api_reports_transactions_get: {
        parameters: {
            query: {
                group: "category" | "counterparty" | "payment_channel" | "movement_kind" | "transfer_direction" | "transfer_scope";
                value: string;
                month_from?: string | null;
                month_to?: string | null;
                statement_id?: string | null;
                currency?: string;
                reporting_category?: ("Groceries" | "Restaurants & Cafes" | "Housing" | "Utilities" | "Transport" | "Health" | "Insurance" | "Subscriptions" | "Shopping" | "Leisure" | "Travel" | "Education" | "Gifts & Donations" | "Taxes" | "Other Expense" | "Salary" | "Interest" | "Other Income" | "Bank Fees") | null;
                movement_kind?: ("Expense" | "Income" | "Transfer" | "Refund" | "Fee") | null;
                payment_channel?: ("MB WAY" | "Card" | "Bank Transfer" | "Direct Debit" | "Cash Withdrawal" | "Other") | null;
                counterparty?: string | null;
                include_provisional?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportTransactionPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_statements_api_statements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementResponse"][];
                };
            };
        };
    };
    upload_statement_api_statements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_statement_api_statements_post"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_statement_api_statements__statement_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_statement_api_statements__statement_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_statement_api_statements__statement_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_transactions_get: {
        parameters: {
            query?: {
                statement_id?: string | null;
                review_only?: boolean;
                booking_date_from?: string | null;
                booking_date_to?: string | null;
                description?: string | null;
                amount_min?: number | string | null;
                amount_max?: number | string | null;
                movement_kind?: ("Expense" | "Income" | "Transfer" | "Refund" | "Fee") | null;
                money_direction?: ("in" | "out") | null;
                classification_status?: ("unclassified" | "classified" | "needs_review") | null;
                payment_channel?: ("MB WAY" | "Card" | "Bank Transfer" | "Direct Debit" | "Cash Withdrawal" | "Other") | null;
                transfer_scope?: ("own_account" | "external_party" | "unknown") | null;
                reporting_category?: ("Groceries" | "Restaurants & Cafes" | "Housing" | "Utilities" | "Transport" | "Health" | "Insurance" | "Subscriptions" | "Shopping" | "Leisure" | "Travel" | "Education" | "Gifts & Donations" | "Taxes" | "Other Expense" | "Salary" | "Interest" | "Other Income" | "Bank Fees") | null;
                currency?: string | null;
                sort?: "booking_date" | "signed_amount" | "description" | "source_ordinal";
                direction?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_api_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_classification_api_transactions__transaction_id__classification_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassificationAcceptanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_transaction_api_transactions__transaction_id__corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transaction_history_api_transactions__transaction_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionRecordResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_transaction_api_transactions__transaction_id__revert_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRevertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
